import test from 'node:test'
import assert from 'node:assert/strict'
import { accountBreakdown, categoryBreakdown, incomeBreakdown, reportCashFlow, reportInsights, reportTotals, resolveReportPeriod, topExpenses } from '../.reports-test-dist/report-calculations.js'

const tx=(overrides={})=>({id:crypto.randomUUID(),transaction_type:'expense',description:'Expense',amount_minor:10000,transaction_date:'2026-09-10',status:'confirmed',category_id:'food',category_name:'Food',category_kind:'expense',from_account_id:'bank',from_account_name:'Bank',to_account_id:null,original_transaction_type:null,original_category_id:null,original_category_name:null,original_from_account_id:null,original_from_account_name:null,...overrides})

test('totals include income and expense, excluding transfer, investment, pending and ignored',()=>{const rows=[tx({transaction_type:'income',amount_minor:50000}),tx({amount_minor:12000}),tx({transaction_type:'transfer',amount_minor:99999}),tx({transaction_type:'investment',amount_minor:99999}),tx({status:'pending',amount_minor:99999}),tx({status:'ignored',amount_minor:99999})];assert.deepEqual(reportTotals(rows,'2026-09-01','2026-09-30'),{totalIncomeMinor:50000,totalExpenseMinor:12000,netCashFlowMinor:38000,savingsRatePercent:76,transactionCount:2})})
test('qualified refund reduces expense and never becomes income',()=>{const rows=[tx({amount_minor:20000}),tx({transaction_type:'refund',amount_minor:5000,category_id:null,category_name:null,category_kind:null,original_transaction_type:'expense',original_category_id:'food',original_category_name:'Food',original_from_account_id:'bank',original_from_account_name:'Bank'})];assert.equal(reportTotals(rows,'2026-09-01','2026-09-30').totalExpenseMinor,15000);assert.equal(reportTotals(rows,'2026-09-01','2026-09-30').totalIncomeMinor,0)})
test('savings rate is null with zero income',()=>assert.equal(reportTotals([tx()],'2026-09-01','2026-09-30').savingsRatePercent,null))
test('category breakdown includes uncategorized and applies refund to original category',()=>{const rows=[tx({amount_minor:20000}),tx({category_id:null,category_name:null,amount_minor:5000}),tx({transaction_type:'refund',amount_minor:2000,original_transaction_type:'expense',original_category_id:'food',original_category_name:'Food'})];assert.deepEqual(categoryBreakdown(rows,'2026-09-01','2026-09-30').map(x=>[x.categoryName,x.amountMinor]),[['Food',18000],['Uncategorized',5000]])})
test('account and income breakdowns use real attribution',()=>{const rows=[tx({amount_minor:20000}),tx({transaction_type:'refund',amount_minor:2000,original_transaction_type:'expense',original_from_account_id:'bank',original_from_account_name:'Bank'}),tx({transaction_type:'income',category_id:null,category_name:null,amount_minor:30000})];assert.deepEqual(accountBreakdown(rows,'2026-09-01','2026-09-30').map(x=>[x.accountName,x.amountMinor]),[['Bank',18000]]);assert.deepEqual(incomeBreakdown(rows,'2026-09-01','2026-09-30').map(x=>[x.categoryName,x.amountMinor]),[['Uncategorized',30000]])})
test('top expenses sort descending and exclude refunds',()=>{const rows=[tx({id:'small',amount_minor:10}),tx({id:'large',amount_minor:30}),tx({id:'refund',transaction_type:'refund',amount_minor:100})];assert.deepEqual(topExpenses(rows,'2026-09-01','2026-09-30').map(x=>x.id),['large','small'])})
test('periods are calendar aligned',()=>{const now=new Date('2026-09-29T12:00:00Z');assert.deepEqual(resolveReportPeriod('thisMonth',now),{start:'2026-09-01',end:'2026-09-29',previousStart:'2026-08-01',previousEnd:'2026-08-31'});assert.equal(resolveReportPeriod('3Months',now).start,'2026-07-01');assert.equal(resolveReportPeriod('6Months',now).start,'2026-04-01');assert.equal(resolveReportPeriod('1Year',now).start,'2025-10-01')})
test('comparison insight uses previous comparable period',()=>{const range=resolveReportPeriod('thisMonth',new Date('2026-09-29T00:00:00Z'));const insights=reportInsights([tx({amount_minor:9000}),tx({amount_minor:10000,transaction_date:'2026-08-10'})],range);const change=insights.find(x=>x.type==='expense_change');assert.equal(change.value,-10);assert.match(change.message,/decreased 10.0%/)})
test('cash flow zero-fills missing months',()=>{const result=reportCashFlow([tx({transaction_date:'2026-07-03'}),tx({transaction_date:'2026-09-03'})],'2026-07-01','2026-09-29');assert.deepEqual(result.map(x=>[x.month,x.expenseMinor]),[['2026-07',10000],['2026-08',0],['2026-09',10000]])})
