import { useState, type FormEvent } from 'react'
import { accounts } from '../../data/mockData'
import type { Category, Transaction, TransactionType } from '../../types/finance'
import { Modal } from './Modal'
const types: TransactionType[] = ['Expense', 'Income', 'Transfer', 'Investment', 'Refund']
const categories: Category[] = ['Shopping','Food','Transport','Salary','Utilities','Transfer','Investments','Housing','Groceries','Education','Refund','Other']
const today = () => new Date().toISOString().slice(0, 10)
export function TransactionForm({ initial, onClose, onSave }: { initial?: Transaction; onClose: () => void; onSave: (item: Transaction) => void }) {
  const [type, setType] = useState<TransactionType>(initial?.type ?? 'Expense'); const [date, setDate] = useState(initial?.date.slice(0,10) ?? today()); const [description, setDescription] = useState(initial?.description ?? ''); const [amount, setAmount] = useState(initial ? String(Math.abs(initial.amount)) : ''); const [account, setAccount] = useState(initial?.account ?? accounts[0].name); const [category, setCategory] = useState<Category>(initial?.category ?? 'Other'); const [notes, setNotes] = useState(initial?.notes ?? ''); const [fromAccount, setFrom] = useState(initial?.fromAccount ?? accounts[0].name); const [toAccount, setTo] = useState(initial?.toAccount ?? accounts[1].name); const [errors, setErrors] = useState<Record<string,string>>({})
  const submit = (event: FormEvent) => { event.preventDefault(); const next: Record<string,string> = {}; if (!description.trim()) next.description = 'Enter a description.'; if (!amount || Number(amount) <= 0) next.amount = 'Enter an amount greater than zero.'; if (!date) next.date = 'Choose a date.'; if (type === 'Transfer' && fromAccount === toAccount) next.transfer = 'From and to accounts must be different.'; setErrors(next); if (Object.keys(next).length) return; const numeric = Number(amount); const selectedAccount = type === 'Transfer' ? `${fromAccount} → ${toAccount}` : account; onSave({ id: initial?.id ?? `TXN-${Date.now().toString().slice(-6)}`, date: `${date}T12:00:00`, description: description.trim(), merchant: notes.trim() || description.trim(), amount: type === 'Expense' || type === 'Investment' ? -numeric : numeric, account: selectedAccount, category: type === 'Transfer' ? 'Transfer' : category, type, status: initial?.status ?? 'Completed', notes: notes.trim() || undefined, fromAccount: type === 'Transfer' ? fromAccount : undefined, toAccount: type === 'Transfer' ? toAccount : undefined }) }
  return <Modal title={initial ? 'Edit transaction' : 'Add transaction'} description={initial ? 'Update this transaction’s details.' : 'Record a new item in your activity.'} onClose={onClose}><form className="transaction-form" onSubmit={submit} noValidate><div className="form-grid"><label><span>Transaction type</span><select value={type} onChange={e => setType(e.target.value as TransactionType)}>{types.map(item => <option key={item}>{item}</option>)}</select></label><label><span>Date</span><input type="date" value={date} onChange={e => setDate(e.target.value)}/>{errors.date && <small className="field-error">{errors.date}</small>}</label><label className="full"><span>Description</span><input value={description} onChange={e => setDescription(e.target.value)} placeholder="e.g. Weekly groceries"/>{errors.description && <small className="field-error">{errors.description}</small>}</label><label><span>Amount (₹)</span><input type="number" min="0.01" step="0.01" inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0.00"/>{errors.amount && <small className="field-error">{errors.amount}</small>}</label>
  {type !== 'Transfer' ? <><label><span>Account</span><select value={account} onChange={e => setAccount(e.target.value)}>{accounts.map(item => <option key={item.id}>{item.name}</option>)}</select></label><label><span>Category</span><select value={category} onChange={e => setCategory(e.target.value as Category)}>{categories.map(item => <option key={item}>{item}</option>)}</select></label></> : <><label><span>From account</span><select value={fromAccount} onChange={e => setFrom(e.target.value)}>{accounts.map(item => <option key={item.id}>{item.name}</option>)}</select></label><label><span>To account</span><select value={toAccount} onChange={e => setTo(e.target.value)}>{accounts.map(item => <option key={item.id}>{item.name}</option>)}</select>{errors.transfer && <small className="field-error">{errors.transfer}</small>}</label></>}
  <label className="full"><span>Notes <em>Optional</em></span><textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder="Add any helpful context" rows={3}/></label></div><footer className="dialog-footer"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" type="submit">{initial ? 'Save changes' : 'Add transaction'}</button></footer></form></Modal>
}
