import { useState, type FormEvent } from 'react'
import type { AccountInput, ApiAccountType } from '../../api/accounts'
import type { Account, AccountType } from '../../types/finance'
import { Modal } from '../transactions/Modal'

const types: AccountType[] = ['Bank Account', 'Credit Card', 'Cash', 'Wallet / Prepaid']
const apiTypes: Record<AccountType, ApiAccountType> = { 'Bank Account':'bank', 'Credit Card':'credit_card', Cash:'cash', 'Wallet / Prepaid':'wallet' }
const toMinor = (value:string) => { const match=value.trim().replace(/,/g,'').match(/^(-?)(\d+)(?:\.(\d{1,2}))?$/); if(!match)return null; const amount=Number(match[2])*100+Number((match[3]??'').padEnd(2,'0')); const minor=match[1]==='-'?-amount:amount; return Number.isSafeInteger(minor)?minor:null }
const fromMinor = (value:number) => { const absolute=Math.abs(value); return `${value<0?'-':''}${Math.floor(absolute/100)}${absolute%100 ? `.${String(absolute%100).padStart(2,'0')}` : ''}` }
export function AccountForm({ initial, saving, requestError, onClose, onSave }: { initial?: Account; saving: boolean; requestError?: string; onClose: () => void; onSave: (account: AccountInput) => void }) {
 const [name,setName]=useState(initial?.name ?? ''); const [institution,setInstitution]=useState(initial?.institution ?? ''); const [type,setType]=useState<AccountType>(initial?.type ?? 'Bank Account'); const [balance,setBalance]=useState(initial?.openingBalanceMinor !== undefined ? fromMinor(initial.type==='Credit Card'?Math.abs(initial.openingBalanceMinor):initial.openingBalanceMinor) : ''); const [openingDate,setOpeningDate]=useState(initial?.openingBalanceDate ?? ''); const [digits,setDigits]=useState(initial?.maskedIdentifier.match(/\d{1,4}$/)?.[0] ?? ''); const [notes,setNotes]=useState(initial?.notes ?? ''); const [limit,setLimit]=useState(initial?.creditLimit ? fromMinor(initial.creditLimit*100) : ''); const [billing,setBilling]=useState(initial?.billingDate ? String(initial.billingDate) : ''); const [due,setDue]=useState(initial?.dueDate ? String(initial.dueDate) : ''); const [errors,setErrors]=useState<Record<string,string>>({})
 const submit=(event:FormEvent)=>{event.preventDefault();const next:Record<string,string>={};const balanceMinor=toMinor(balance);const limitMinor=limit?toMinor(limit):null;if(!name.trim())next.name='Enter an account name.';if(balanceMinor===null)next.balance='Enter a valid rupee amount with up to 2 decimals.';if(type==='Credit Card'&&balanceMinor!==null&&balanceMinor<0)next.balance='Enter the amount owed as a positive number.';if(digits&&!/^\d{1,4}$/.test(digits))next.digits='Enter up to 4 digits.';if(type==='Credit Card'&&(limitMinor===null||limitMinor<0))next.limit='Enter a valid credit limit.';for(const [key,value] of [['billing',billing],['due',due]])if(value&&(!Number.isInteger(Number(value))||Number(value)<1||Number(value)>31))next[key]='Enter a day from 1 to 31.';setErrors(next);if(Object.keys(next).length||balanceMinor===null)return;onSave({name:name.trim(),institution:institution.trim(),accountType:apiTypes[type],last4:digits||null,openingBalanceMinor:type==='Credit Card'?-balanceMinor:balanceMinor,openingBalanceDate:openingDate||null,notes:notes.trim()||null,creditLimitMinor:type==='Credit Card'?limitMinor:null,billingDay:type==='Credit Card'&&billing?Number(billing):null,dueDay:type==='Credit Card'&&due?Number(due):null,isActive:initial?.status!=='Inactive'})}
 return <Modal title={initial?'Edit account':'Add account'} description={type==='Credit Card'?'Enter the opening amount owed as a positive number. Only the last four digits are stored.':'Keep the details brief — only the last four digits are stored.'} onClose={onClose}>
  <form className="transaction-form" onSubmit={submit}><div className="form-grid"><label><span>Account Name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Salary Account" autoFocus/>{errors.name&&<small className="field-error">{errors.name}</small>}</label><label><span>Institution</span><input value={institution} onChange={e=>setInstitution(e.target.value)} placeholder="e.g. HDFC Bank"/></label><label><span>Account Type</span><select value={type} onChange={e=>setType(e.target.value as AccountType)}>{types.map(item=><option key={item}>{item}</option>)}</select></label><label><span>Opening Balance</span><input inputMode="decimal" value={balance} onChange={e=>setBalance(e.target.value)} placeholder="0.00"/>{errors.balance&&<small className="field-error">{errors.balance}</small>}</label><label><span>Opening Balance Date <em>Optional</em></span><input type="date" value={openingDate} onChange={e=>setOpeningDate(e.target.value)}/></label><label><span>Last 4 digits <em>Optional</em></span><input inputMode="numeric" maxLength={4} value={digits} onChange={e=>setDigits(e.target.value.replace(/\D/g,'').slice(0,4))} placeholder="1234"/>{errors.digits&&<small className="field-error">{errors.digits}</small>}</label>{type==='Credit Card'&&<><label><span>Credit Limit</span><input inputMode="decimal" value={limit} onChange={e=>setLimit(e.target.value)} placeholder="100000"/>{errors.limit&&<small className="field-error">{errors.limit}</small>}</label><label><span>Billing Day</span><input type="number" min="1" max="31" value={billing} onChange={e=>setBilling(e.target.value)}/>{errors.billing&&<small className="field-error">{errors.billing}</small>}</label><label><span>Due Day</span><input type="number" min="1" max="31" value={due} onChange={e=>setDue(e.target.value)}/>{errors.due&&<small className="field-error">{errors.due}</small>}</label></>}<label className="full"><span>Notes <em>Optional</em></span><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Anything useful to remember"/></label>{requestError&&<div className="api-feedback error full" role="alert">{requestError}</div>}</div><footer className="dialog-footer"><button type="button" className="secondary-button" onClick={onClose} disabled={saving}>Cancel</button><button className="primary-button" type="submit" disabled={saving}>{saving?'Saving…':initial?'Save changes':'Add account'}</button></footer></form>
 </Modal>
}
