import { useState, type FormEvent } from 'react'
import type { Account, AccountType } from '../../types/finance'
import { Modal } from '../transactions/Modal'

const types: AccountType[] = ['Bank Account', 'Credit Card', 'Cash', 'Wallet / Prepaid']
const colors: Account['color'][] = ['lime','violet','blue','slate']
export function AccountForm({ initial, onClose, onSave }: { initial?: Account; onClose: () => void; onSave: (account: Account) => void }) {
 const [name,setName]=useState(initial?.name ?? ''); const [institution,setInstitution]=useState(initial?.institution ?? ''); const [type,setType]=useState<AccountType>(initial?.type ?? 'Bank Account'); const [balance,setBalance]=useState(initial ? String(Math.abs(initial.balance)) : ''); const [digits,setDigits]=useState(initial?.maskedIdentifier.match(/\d{4}$/)?.[0] ?? ''); const [notes,setNotes]=useState(initial?.notes ?? ''); const [limit,setLimit]=useState(initial?.creditLimit ? String(initial.creditLimit) : ''); const [billing,setBilling]=useState(initial?.billingDate ? String(initial.billingDate) : ''); const [due,setDue]=useState(initial?.dueDate ? String(initial.dueDate) : ''); const [errors,setErrors]=useState<Record<string,string>>({})
 const submit=(event:FormEvent)=>{event.preventDefault();const next:Record<string,string>={};if(!name.trim())next.name='Enter an account name.';if(!institution.trim())next.institution='Enter an institution.';if(!balance || Number(balance)<0)next.balance='Enter a valid balance.';if(type!=='Cash'&&!/^\d{4}$/.test(digits))next.digits='Enter exactly 4 digits.';if(type==='Credit Card'&&(!limit||Number(limit)<=0))next.limit='Enter a valid credit limit.';setErrors(next);if(Object.keys(next).length)return;onSave({id:initial?.id??`account-${Date.now()}`,name:name.trim(),institution:institution.trim(),type,maskedIdentifier:type==='Cash'?'Cash on hand':`•••• ${digits}`,balance:type==='Credit Card'?-Math.abs(Number(balance)):Number(balance),color:initial?.color??colors[Math.floor(Math.random()*colors.length)],status:initial?.status??'Active',notes:notes.trim()||undefined,creditLimit:type==='Credit Card'?Number(limit):undefined,billingDate:type==='Credit Card'?Number(billing)||undefined:undefined,dueDate:type==='Credit Card'?Number(due)||undefined:undefined})}
 return <Modal title={initial?'Edit account':'Add account'} description="Keep the details brief — only the last four digits are stored." onClose={onClose}>
  <form className="transaction-form" onSubmit={submit}><div className="form-grid"><label><span>Account Name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Salary Account" autoFocus/>{errors.name&&<small className="field-error">{errors.name}</small>}</label><label><span>Institution</span><input value={institution} onChange={e=>setInstitution(e.target.value)} placeholder="e.g. HDFC Bank"/>{errors.institution&&<small className="field-error">{errors.institution}</small>}</label><label><span>Account Type</span><select value={type} onChange={e=>setType(e.target.value as AccountType)}>{types.map(item=><option key={item}>{item}</option>)}</select></label><label><span>{type==='Credit Card'?'Current Outstanding':'Opening / Current Balance'}</span><input type="number" min="0" value={balance} onChange={e=>setBalance(e.target.value)} placeholder="0"/>{errors.balance&&<small className="field-error">{errors.balance}</small>}</label>{type!=='Cash'&&<label><span>Last 4 digits</span><input inputMode="numeric" maxLength={4} value={digits} onChange={e=>setDigits(e.target.value.replace(/\D/g,'').slice(0,4))} placeholder="1234"/>{errors.digits&&<small className="field-error">{errors.digits}</small>}</label>}{type==='Credit Card'&&<><label><span>Credit Limit</span><input type="number" min="0" value={limit} onChange={e=>setLimit(e.target.value)} placeholder="100000"/>{errors.limit&&<small className="field-error">{errors.limit}</small>}</label><label><span>Billing Date <em>Day of month</em></span><input type="number" min="1" max="31" value={billing} onChange={e=>setBilling(e.target.value)}/></label><label><span>Due Date <em>Day of month</em></span><input type="number" min="1" max="31" value={due} onChange={e=>setDue(e.target.value)}/></label></>}<label className="full"><span>Notes <em>Optional</em></span><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Anything useful to remember"/></label></div><footer className="dialog-footer"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" type="submit">{initial?'Save changes':'Add account'}</button></footer></form>
 </Modal>
}
