import { Plus } from 'lucide-react'
import { useState } from 'react'
import { useOutletContext } from 'react-router-dom'
import { AssetAllocation } from '../components/investments/AssetAllocation'
import { InvestmentActivity } from '../components/investments/InvestmentActivity'
import { InvestmentDetails } from '../components/investments/InvestmentDetails'
import { InvestmentForm } from '../components/investments/InvestmentForm'
import { InvestmentSummary } from '../components/investments/InvestmentSummary'
import { InvestmentTable } from '../components/investments/InvestmentTable'
import { PortfolioPerformance } from '../components/investments/PortfolioPerformance'
import { PageHeader } from '../components/layout/PageHeader'
import { ConfirmDialog } from '../components/transactions/ConfirmDialog'
import { investments as mockInvestments } from '../data/mockData'
import type { Investment } from '../types/finance'
export function InvestmentsPage(){const {openMenu}=useOutletContext<{openMenu:()=>void}>();const [investments,setInvestments]=useState<Investment[]>(mockInvestments);const [viewing,setViewing]=useState<Investment>();const [editing,setEditing]=useState<Investment|null>();const [deleting,setDeleting]=useState<Investment>();const save=(item:Investment)=>{setInvestments(old=>old.some(i=>i.id===item.id)?old.map(i=>i.id===item.id?item:i):[item,...old]);setEditing(undefined)};return <><PageHeader title="Investments" eyebrow="Wealth overview" onMenu={openMenu}/><main className="page-body investments-page"><div className="investments-intro"><div><h2>Investments</h2><p>Track your portfolio, performance and long-term wealth.</p></div><button className="primary-button" onClick={()=>setEditing(null)}><Plus/>Add Investment</button></div><InvestmentSummary investments={investments}/><div className="investment-overview-grid"><PortfolioPerformance/><AssetAllocation investments={investments}/></div><InvestmentTable investments={investments} onView={setViewing} onEdit={setEditing} onDelete={setDeleting}/><InvestmentActivity/></main><button className="investments-mobile-add" onClick={()=>setEditing(null)} aria-label="Add investment"><Plus/></button>{editing!==undefined&&<InvestmentForm initial={editing??undefined} onClose={()=>setEditing(undefined)} onSave={save}/>} {viewing&&<InvestmentDetails investment={viewing} onClose={()=>setViewing(undefined)} onEdit={()=>{setEditing(viewing);setViewing(undefined)}}/>}{deleting&&<ConfirmDialog subject="investment" name={deleting.name} onCancel={()=>setDeleting(undefined)} onConfirm={()=>{setInvestments(old=>old.filter(i=>i.id!==deleting.id));setDeleting(undefined)}}/>}</>}
