import { ArrowDownLeft, ArrowLeftRight, ArrowUpRight, ListChecks, Plus } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useOutletContext } from 'react-router-dom'
import { getAccounts, type AccountDto } from '../api/accounts'
import { getCategories, type CategoryDto } from '../api/categories'
import { createTransaction, getTransactions, removeTransaction, updateTransaction, updateTransactionStatus, type TransactionDto, type TransactionInput } from '../api/transactions'
import { PageHeader } from '../components/layout/PageHeader'
import { ConfirmDialog } from '../components/transactions/ConfirmDialog'
import { TransactionDetails } from '../components/transactions/TransactionDetails'
import { emptyFilters, TransactionFilters, type FilterState } from '../components/transactions/TransactionFilters'
import { TransactionForm } from '../components/transactions/TransactionForm'
import { TransactionTable } from '../components/transactions/TransactionTable'
import { formatCurrency } from '../lib/format'
import type { Transaction } from '../types/finance'

const titleCase = (value: string) => `${value[0].toUpperCase()}${value.slice(1)}`

function toView(dto: TransactionDto, accounts: AccountDto[], categories: CategoryDto[]): Transaction {
  const from = accounts.find(item => item.id === dto.fromAccountId)?.name
  const to = accounts.find(item => item.id === dto.toAccountId)?.name
  const type = titleCase(dto.transactionType) as Transaction['type']
  const account = dto.transactionType === 'transfer' ? `${from ?? 'Unknown'} → ${to ?? 'Unknown'}` : (from ?? to ?? 'Unknown account')
  return { id: dto.id, date: `${dto.transactionDate}T12:00:00`, description: dto.description, merchant: dto.notes ?? dto.description, category: categories.find(item => item.id === dto.categoryId)?.name ?? (dto.transactionType === 'transfer' ? 'Transfer' : 'Uncategorised'), account, type, amount: dto.amountMinor / 100, amountMinor: dto.amountMinor, status: titleCase(dto.status) as Transaction['status'], source: dto.source, notes: dto.notes ?? undefined, fromAccount: from, toAccount: to, fromAccountId: dto.fromAccountId, toAccountId: dto.toAccountId, categoryId: dto.categoryId, originalTransactionId: dto.originalTransactionId }
}

export function TransactionsPage() {
  const { openMenu } = useOutletContext<{ openMenu: () => void }>()
  const [dtos, setDtos] = useState<TransactionDto[]>([]); const [accounts, setAccounts] = useState<AccountDto[]>([]); const [categories, setCategories] = useState<CategoryDto[]>([])
  const [filters, setFilters] = useState<FilterState>(emptyFilters); const [form, setForm] = useState<{ mode: 'add' | 'edit'; item?: Transaction }>(); const [viewing, setViewing] = useState<Transaction>(); const [deleting, setDeleting] = useState<Transaction>()
  const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState<string>(); const [mutationError, setMutationError] = useState<string>(); const [saving, setSaving] = useState(false); const [isDeleting, setIsDeleting] = useState(false)
  const load = async () => { setLoading(true); try { const [nextTransactions, nextAccounts, nextCategories] = await Promise.all([getTransactions(), getAccounts(), getCategories()]); setDtos(nextTransactions); setAccounts(nextAccounts); setCategories(nextCategories); setLoadError(undefined) } catch (error) { setLoadError(error instanceof Error ? error.message : 'Could not load transactions.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const items = useMemo(() => dtos.map(item => toView(item, accounts, categories)), [dtos, accounts, categories])
  const accountNames = useMemo(() => accounts.map(item => item.name).sort(), [accounts]); const categoryNames = useMemo(() => categories.map(item => item.name).sort(), [categories])
  const visible = useMemo(() => items.filter(item => { const text = `${item.description} ${item.merchant} ${item.category} ${item.account}`.toLowerCase(); const cutoff = filters.range === 'All' ? 0 : Date.now() - Number(filters.range) * 86400000; return (!filters.search || text.includes(filters.search.toLowerCase())) && (filters.type === 'All' || item.type === filters.type) && (filters.category === 'All' || item.category === filters.category) && (filters.account === 'All' || item.account.includes(filters.account)) && (filters.source === 'All' || item.source === filters.source.toLowerCase()) && (filters.status === 'All' || item.status === filters.status) && (!cutoff || new Date(item.date).getTime() >= cutoff) }), [items, filters])
  const pendingSms = useMemo(() => items.filter(item => item.source === 'sms' && item.status === 'Pending'), [items])
  const confirmed = items.filter(item => item.status === 'Confirmed')
  const totals = useMemo(() => ({ income: confirmed.filter(item => item.type === 'Income' || item.type === 'Refund').reduce((sum, item) => sum + item.amount, 0), expenses: confirmed.filter(item => item.type === 'Expense' || item.type === 'Investment').reduce((sum, item) => sum + item.amount, 0) }), [items])
  const save = async (value: TransactionInput) => { setSaving(true); setMutationError(undefined); try { const saved = form?.item ? await updateTransaction(form.item.id, value) : await createTransaction(value); setDtos(old => form?.item ? old.map(item => item.id === saved.id ? saved : item) : [saved, ...old]); setForm(undefined) } catch (error) { setMutationError(error instanceof Error ? error.message : 'Could not save the transaction.') } finally { setSaving(false) } }
  const confirmDelete = async () => { if (!deleting) return; setIsDeleting(true); setMutationError(undefined); try { await removeTransaction(deleting.id); setDtos(old => old.filter(item => item.id !== deleting.id)); setDeleting(undefined) } catch (error) { setMutationError(error instanceof Error ? error.message : 'Could not delete the transaction.') } finally { setIsDeleting(false) } }
  const changeStatus = async (item: Transaction, status: 'confirmed' | 'ignored') => { setMutationError(undefined); try { const saved = await updateTransactionStatus(item.id, status); setDtos(old => old.map(dto => dto.id === saved.id ? saved : dto)) } catch (error) { setMutationError(error instanceof Error ? error.message : 'Could not update the transaction.'); if (status === 'confirmed') setForm({ mode: 'edit', item }) } }
  return <><PageHeader title="Transactions" eyebrow="Money movement" onMenu={openMenu}/><main className="page-body transactions-page"><div className="transaction-intro"><div><h2>Transactions</h2><p>Track and manage your financial activity across every account.</p></div><button className="primary-button" onClick={() => { setMutationError(undefined); setForm({ mode: 'add' }) }}><Plus/> <span>Add transaction</span></button></div>
    {loadError && <div className="api-feedback error" role="alert"><span>{loadError}</span><button className="secondary-button" onClick={() => void load()}>Try again</button></div>}
    {mutationError && !form && !deleting && <div className="api-feedback error" role="alert"><span>{mutationError}</span></div>}
    {pendingSms.length > 0 && <section className="needs-review panel"><div><h3>Needs Review</h3><p>{pendingSms.length} SMS {pendingSms.length === 1 ? 'transaction needs' : 'transactions need'} your attention.</p></div><div className="review-list">{pendingSms.map(item => <article key={item.id}><div><strong>{item.description}</strong><small>{item.date.slice(0, 10)} · {item.account} · {item.category}</small></div><strong>{formatCurrency(item.amount)}</strong><div className="review-actions"><button className="secondary-button" onClick={() => setViewing(item)}>Review</button><button className="secondary-button" onClick={() => { setMutationError(undefined); setForm({ mode: 'edit', item }) }}>Edit</button><button className="primary-button" onClick={() => void changeStatus(item, 'confirmed')}>Confirm</button><button className="secondary-button" onClick={() => void changeStatus(item, 'ignored')}>Ignore</button></div></article>)}</div></section>}
    <section className="transaction-summary" aria-label="Transaction summary"><article><span className="summary-mini-icon income"><ArrowDownLeft/></span><div><p>Total income</p><strong>{formatCurrency(totals.income)}</strong></div></article><article><span className="summary-mini-icon expense"><ArrowUpRight/></span><div><p>Total expenses</p><strong>{formatCurrency(totals.expenses)}</strong></div></article><article><span className="summary-mini-icon flow"><ArrowLeftRight/></span><div><p>Net cash flow</p><strong className={totals.income - totals.expenses >= 0 ? 'positive-text' : 'negative-text'}>{totals.income - totals.expenses >= 0 ? '+' : '−'}{formatCurrency(totals.income - totals.expenses)}</strong></div></article><article><span className="summary-mini-icon count"><ListChecks/></span><div><p>Transactions</p><strong>{items.length}</strong></div></article></section>
    <section className="transactions-panel panel"><div className="transactions-panel-head"><div><h3>All activity</h3><p>{loading ? 'Loading transactions…' : `${visible.length} ${visible.length === 1 ? 'transaction' : 'transactions'} found`}</p></div></div><TransactionFilters value={filters} onChange={setFilters} categories={categoryNames} accounts={accountNames}/>{loading && !items.length ? <div className="empty-state"><h3>Loading transactions…</h3><p>Your activity will appear in a moment.</p></div> : <TransactionTable items={visible} onView={setViewing} onEdit={item => { setMutationError(undefined); setForm({ mode: 'edit', item }) }} onDelete={item => { setMutationError(undefined); setDeleting(item) }} onConfirm={item => void changeStatus(item, 'confirmed')} onIgnore={item => void changeStatus(item, 'ignored')}/>}<footer className="table-footer">Showing {visible.length} of {items.length} transactions</footer></section></main>
    {form && <TransactionForm initial={form.item} accounts={accounts} categories={categories} saving={saving} requestError={mutationError} onClose={() => setForm(undefined)} onSave={save}/>} {viewing && <TransactionDetails item={viewing} onClose={() => setViewing(undefined)} onEdit={() => { setForm({ mode: 'edit', item: viewing }); setViewing(undefined) }}/>} {deleting && <ConfirmDialog name={deleting.description} busy={isDeleting} error={mutationError} onCancel={() => setDeleting(undefined)} onConfirm={() => void confirmDelete()}/>}</>
}
