import { ArrowRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { AccountDto } from '../../api/accounts'
import type { TransactionDto } from '../../api/transactions'
import { formatDate, formatMinorCurrency } from '../../lib/format'
import type { TransactionType } from '../../types/finance'
import { TransactionIcon } from '../transactions/TransactionIcon'
import { TypeBadge } from '../transactions/TypeBadge'
const titleCase=(v:string)=>`${v[0].toUpperCase()}${v.slice(1)}` as TransactionType
export function RecentTransactions({transactions,accounts}:{transactions:TransactionDto[];accounts:AccountDto[]}){const name=(id:string|null)=>accounts.find(a=>a.id===id)?.name??'Unknown account';return <section className="panel recent-panel"><div className="section-heading"><div><p className="eyebrow">Latest activity</p><h2>Recent transactions</h2></div><Link className="text-link" to="/transactions">View all <ArrowRight size={16}/></Link></div>{!transactions.length?<div className="dashboard-panel-empty"><strong>No confirmed transactions</strong><small>Your latest confirmed activity will appear here.</small></div>:<div className="recent-list">{transactions.map(item=>{const type=titleCase(item.transactionType);const positive=item.transactionType==='income'||item.transactionType==='refund';const account=item.transactionType==='transfer'?`${name(item.fromAccountId)} → ${name(item.toAccountId)}`:name(item.fromAccountId??item.toAccountId);return <article className="recent-row" key={item.id}><TransactionIcon type={type}/><div className="recent-name"><strong>{item.description}</strong><small>{item.notes??'No note'}</small></div><TypeBadge type={type}/><div className="recent-date"><span>{formatDate(`${item.transactionDate}T12:00:00`)}</span><small>{account}</small></div><strong className={`amount ${positive?'positive':item.transactionType==='transfer'?'neutral':''}`}>{positive?'+':item.transactionType==='transfer'?'':'−'}{formatMinorCurrency(item.amountMinor)}</strong></article>})}</div>}</section>}
